version: '3.8'
services:
  spring-app:
    image: central-bank-rest-src
    container_name: central-bank-rest-src
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file://data//centralbankdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"