-- DROP TABLE IF EXISTS participant_info;
CREATE TABLE IF NOT EXISTS participant_info
(
    uuid               UUID PRIMARY KEY,
    name_p             VARCHAR(160) NOT NULL,
    engl_name          VARCHAR(140),
    reg_n              CHAR(9),
    cntr_cd            CHAR(2),
    rgn                CHAR(2)      NOT NULL,
    ind                CHAR(6),
    tnp                CHAR(5),
    nnp                VARCHAR(25),
    adr                VARCHAR(160),
    prnt_BIC           CHAR(9),
    date_in            DATE         NOT NULL,
    date_out           DATE,
    pt_type            CHAR(2)      NOT NULL,
    srvcs              CHAR(1)      NOT NULL,
    xch_type           CHAR(1)      NOT NULL,
    uid                CHAR(10)     NOT NULL,
    participant_status CHAR(4),
    bic_directory_entry_uuid UUID,
    CONSTRAINT fk_participant_info_bic_directory_entry_uuid FOREIGN KEY (bic_directory_entry_uuid) REFERENCES bic_directory_entry (uuid),
    CONSTRAINT name_p_check CHECK (length(name_p) >= 1 AND length(name_p) <= 160),
    CONSTRAINT engl_name_check CHECK (length(engl_name) >= 1 AND length(engl_name) <= 140),
    CONSTRAINT reg_n_check CHECK (length(reg_n) >= 1 AND length(reg_n) <= 9),
    CONSTRAINT cntr_cd_check CHECK (length(cntr_cd) = 2),
    CONSTRAINT rgn_check CHECK (length(rgn) = 2),
    CONSTRAINT ind_check CHECK (length(ind) >= 1 AND length(ind) <= 6),
    CONSTRAINT tnp_check CHECK (length(tnp) >= 1 AND length(tnp) <= 5),
    CONSTRAINT nnp_check CHECK (length(nnp) >= 1 AND length(nnp) <= 25),
    CONSTRAINT adr_check CHECK (length(adr) >= 1 AND length(adr) <= 160),
    CONSTRAINT prnt_BIC_check CHECK (length(prnt_BIC) = 9),
    CONSTRAINT pt_type_check CHECK (length(pt_type) = 2),
    CONSTRAINT srvcs_check CHECK (length(srvcs) = 1),
    CONSTRAINT xch_type_check CHECK (length(xch_type) = 1),
    CONSTRAINT uid_check CHECK (uid ~ '^[0-9]{10}$'),
    CONSTRAINT participant_status_check CHECK (length(participant_status) = 4)
);