
    create table acc_rstr_list (
        acc_rstr varchar(4) not null,
        acc_rstr_date date not null,
        successor_bic integer check ((successor_bic<=999999999) and (successor_bic>=100000000)),
        accounts_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table accounts (
        account_status varchar(4),
        ck varchar(2),
        date_in date not null,
        date_out date,
        regulation_account_type varchar(4) not null,
        account_cbrbic varchar(9) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        account varchar(20) not null,
        primary key (uuid)
    );

    create table authorities (
        authority_id integer generated by default as identity,
        authority varchar(255),
        primary key (authority_id)
    );

    create table bic_directory_entry (
        change_type varchar(4),
        bic varchar(9) not null,
        root_entity_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table ed807 (
        business_day date not null,
        directory_version integer check ((directory_version>=0) and (directory_version<=99)),
        ed_date date not null,
        ed_no integer not null,
        created_at timestamp(6) not null,
        creation_date_time timestamp(6) with time zone not null,
        ed_author bigint not null check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed_receiver bigint check ((ed_receiver<=9999999999) and (ed_receiver>=1000000000)),
        updated_at timestamp(6),
        uuid uuid not null,
        created_by varchar(255) not null,
        creation_reason varchar(255) not null,
        file_name varchar(255) not null,
        info_type_code varchar(255) not null,
        updated_by varchar(255),
        primary key (uuid)
    );

    create table initial_ed (
        ed_date date not null,
        ed_no integer not null check ((ed_no<=999999999) and (ed_no>=1)),
        ed_author bigint not null unique check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table part_info (
        part_aggregate_id numeric(27,0) not null,
        part_no integer not null,
        part_quantity integer not null,
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table participant_info (
        cntr_cd varchar(2),
        date_in date not null,
        date_out date,
        participant_status varchar(4),
        pt_type varchar(2) not null,
        rgn varchar(2) not null,
        srvcs varchar(1) not null,
        xch_type varchar(1) not null,
        tnp varchar(5),
        ind varchar(6),
        prnt_bic varchar(9),
        reg_n varchar(9),
        bic_directory_entry_uuid uuid unique,
        uuid uuid not null,
        nnp varchar(25),
        engl_name varchar(140),
        adr varchar(160),
        name_p varchar(160) not null,
        uid varchar(255) not null,
        primary key (uuid)
    );

    create table rstr_list (
        rstr varchar(4) not null,
        rstr_date date not null,
        participant_info_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table swbics (
        default_swbic boolean not null,
        swbic varchar(11) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table user_authority_function (
        authority_id integer not null,
        user_id bigint not null,
        primary key (authority_id, user_id)
    );

    create table users (
        user_id bigint generated by default as identity,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (user_id)
    );

    alter table if exists acc_rstr_list 
       add constraint FKrj6pnwmxn6h6qq1q9nj4t1te7 
       foreign key (accounts_uuid) 
       references accounts;

    alter table if exists accounts 
       add constraint FKhueic73i7wuk4dys7ferx2asm 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists bic_directory_entry 
       add constraint FK7s4bc5qe80x29qbp8kqxrtsgg 
       foreign key (root_entity_uuid) 
       references ed807;

    alter table if exists initial_ed 
       add constraint FKk9crfdsaed29c1lw4t531vb08 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists part_info 
       add constraint FKdqcu11tyqr1raymltu10t1b1n 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists participant_info 
       add constraint FKmnpisqk63o1el55k0gsnty109 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists rstr_list 
       add constraint FKkdnaka1sesrwxbjml61t5xr2p 
       foreign key (participant_info_uuid) 
       references participant_info;

    alter table if exists swbics 
       add constraint FK8ws6uobq79xwcng67h1dwv3vg 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists user_authority_function 
       add constraint FKqubfm66mfbvt9de6i8r72mc4b 
       foreign key (authority_id) 
       references authorities;

    alter table if exists user_authority_function 
       add constraint FKrvgos00m72pdmvfyhu4af7s7b 
       foreign key (user_id) 
       references users;

    create table acc_rstr_list (
        acc_rstr varchar(4) not null,
        acc_rstr_date date not null,
        successor_bic integer check ((successor_bic<=999999999) and (successor_bic>=100000000)),
        accounts_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table accounts (
        account_status varchar(4),
        ck varchar(2),
        date_in date not null,
        date_out date,
        regulation_account_type varchar(4) not null,
        account_cbrbic varchar(9) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        account varchar(20) not null,
        primary key (uuid)
    );

    create table authorities (
        authority_id integer generated by default as identity,
        authority varchar(255),
        primary key (authority_id)
    );

    create table bic_directory_entry (
        change_type varchar(4),
        bic varchar(9) not null,
        ed807entity_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table ed807 (
        business_day date not null,
        directory_version integer check ((directory_version>=0) and (directory_version<=99)),
        ed_date date not null,
        ed_no integer not null,
        created_at timestamp(6) not null,
        creation_date_time timestamp(6) with time zone not null,
        ed_author bigint not null check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed_receiver bigint check ((ed_receiver<=9999999999) and (ed_receiver>=1000000000)),
        updated_at timestamp(6),
        uuid uuid not null,
        created_by varchar(255) not null,
        creation_reason varchar(255) not null,
        file_name varchar(255) not null,
        info_type_code varchar(255) not null,
        updated_by varchar(255),
        primary key (uuid)
    );

    create table initial_ed (
        ed_date date not null,
        ed_no integer not null check ((ed_no<=999999999) and (ed_no>=1)),
        ed_author bigint not null unique check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table part_info (
        part_aggregate_id numeric(27,0) not null,
        part_no integer not null,
        part_quantity integer not null,
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table participant_info (
        cntr_cd varchar(2),
        date_in date not null,
        date_out date,
        participant_status varchar(4),
        pt_type varchar(2) not null,
        rgn varchar(2) not null,
        srvcs varchar(1) not null,
        xch_type varchar(1) not null,
        tnp varchar(5),
        ind varchar(6),
        prnt_bic varchar(9),
        reg_n varchar(9),
        bic_directory_entry_uuid uuid unique,
        uuid uuid not null,
        nnp varchar(25),
        engl_name varchar(140),
        adr varchar(160),
        name_p varchar(160) not null,
        uid varchar(255) not null,
        primary key (uuid)
    );

    create table rstr_list (
        rstr varchar(4) not null,
        rstr_date date not null,
        participant_info_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table swbics (
        default_swbic boolean not null,
        swbic varchar(11) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table user_authority_function (
        authority_id integer not null,
        user_id bigint not null,
        primary key (authority_id, user_id)
    );

    create table users (
        user_id bigint generated by default as identity,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (user_id)
    );

    alter table if exists acc_rstr_list 
       add constraint FKrj6pnwmxn6h6qq1q9nj4t1te7 
       foreign key (accounts_uuid) 
       references accounts;

    alter table if exists accounts 
       add constraint FKhueic73i7wuk4dys7ferx2asm 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists bic_directory_entry 
       add constraint FKs7t1uhsqwrd1mrwa62o89n6c9 
       foreign key (ed807entity_uuid) 
       references ed807;

    alter table if exists initial_ed 
       add constraint FKk9crfdsaed29c1lw4t531vb08 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists part_info 
       add constraint FKdqcu11tyqr1raymltu10t1b1n 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists participant_info 
       add constraint FKmnpisqk63o1el55k0gsnty109 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists rstr_list 
       add constraint FKkdnaka1sesrwxbjml61t5xr2p 
       foreign key (participant_info_uuid) 
       references participant_info;

    alter table if exists swbics 
       add constraint FK8ws6uobq79xwcng67h1dwv3vg 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists user_authority_function 
       add constraint FKqubfm66mfbvt9de6i8r72mc4b 
       foreign key (authority_id) 
       references authorities;

    alter table if exists user_authority_function 
       add constraint FKrvgos00m72pdmvfyhu4af7s7b 
       foreign key (user_id) 
       references users;

    create table acc_rstr_list (
        acc_rstr varchar(4) not null,
        acc_rstr_date date not null,
        successor_bic integer check ((successor_bic<=999999999) and (successor_bic>=100000000)),
        accounts_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table accounts (
        account_status varchar(4),
        ck varchar(2),
        date_in date not null,
        date_out date,
        regulation_account_type varchar(4) not null,
        account_cbrbic varchar(9) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        account varchar(20) not null,
        primary key (uuid)
    );

    create table authorities (
        authority_id integer generated by default as identity,
        authority varchar(255),
        primary key (authority_id)
    );

    create table bic_directory_entry (
        change_type varchar(4),
        bic varchar(9) not null,
        ed807_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table ed807 (
        business_day date not null,
        directory_version integer check ((directory_version>=0) and (directory_version<=99)),
        ed_date date not null,
        ed_no integer not null,
        created_at timestamp(6) not null,
        creation_date_time timestamp(6) with time zone not null,
        ed_author bigint not null check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed_receiver bigint check ((ed_receiver<=9999999999) and (ed_receiver>=1000000000)),
        updated_at timestamp(6),
        uuid uuid not null,
        created_by varchar(255) not null,
        creation_reason varchar(255) not null,
        file_name varchar(255) not null,
        info_type_code varchar(255) not null,
        updated_by varchar(255),
        primary key (uuid)
    );

    create table initial_ed (
        ed_date date not null,
        ed_no integer not null check ((ed_no<=999999999) and (ed_no>=1)),
        ed_author bigint not null unique check ((ed_author<=9999999999) and (ed_author>=1000000000)),
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table part_info (
        part_aggregate_id numeric(27,0) not null,
        part_no integer not null,
        part_quantity integer not null,
        ed807_uuid uuid unique,
        uuid uuid not null,
        primary key (uuid)
    );

    create table participant_info (
        cntr_cd varchar(2),
        date_in date not null,
        date_out date,
        participant_status varchar(4),
        pt_type varchar(2) not null,
        rgn varchar(2) not null,
        srvcs varchar(1) not null,
        xch_type varchar(1) not null,
        tnp varchar(5),
        ind varchar(6),
        prnt_bic varchar(9),
        reg_n varchar(9),
        bic_directory_entry_uuid uuid unique,
        uuid uuid not null,
        nnp varchar(25),
        engl_name varchar(140),
        adr varchar(160),
        name_p varchar(160) not null,
        uid varchar(255) not null,
        primary key (uuid)
    );

    create table rstr_list (
        rstr varchar(4) not null,
        rstr_date date not null,
        participant_info_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table swbics (
        default_swbic boolean not null,
        swbic varchar(11) not null,
        bic_directory_entry_uuid uuid,
        uuid uuid not null,
        primary key (uuid)
    );

    create table user_authority_function (
        authority_id integer not null,
        user_id bigint not null,
        primary key (authority_id, user_id)
    );

    create table users (
        user_id bigint generated by default as identity,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (user_id)
    );

    alter table if exists acc_rstr_list 
       add constraint FKrj6pnwmxn6h6qq1q9nj4t1te7 
       foreign key (accounts_uuid) 
       references accounts;

    alter table if exists accounts 
       add constraint FKhueic73i7wuk4dys7ferx2asm 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists bic_directory_entry 
       add constraint FKlq5q80x4qkexng1hgfl7lpypr 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists initial_ed 
       add constraint FKk9crfdsaed29c1lw4t531vb08 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists part_info 
       add constraint FKdqcu11tyqr1raymltu10t1b1n 
       foreign key (ed807_uuid) 
       references ed807;

    alter table if exists participant_info 
       add constraint FKmnpisqk63o1el55k0gsnty109 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists rstr_list 
       add constraint FKkdnaka1sesrwxbjml61t5xr2p 
       foreign key (participant_info_uuid) 
       references participant_info;

    alter table if exists swbics 
       add constraint FK8ws6uobq79xwcng67h1dwv3vg 
       foreign key (bic_directory_entry_uuid) 
       references bic_directory_entry;

    alter table if exists user_authority_function 
       add constraint FKqubfm66mfbvt9de6i8r72mc4b 
       foreign key (authority_id) 
       references authorities;

    alter table if exists user_authority_function 
       add constraint FKrvgos00m72pdmvfyhu4af7s7b 
       foreign key (user_id) 
       references users;
